<?php
/**
 * LINE OA Manager - Configuration
 * Generated by Installation Wizard
 */

// Set UTF-8 encoding
mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');
header('Content-Type: text/html; charset=utf-8');

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

// Start session
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database Credentials
define('DB_HOST', 'localhost');
define('DB_NAME', 'likesmsn_api');
define('DB_USER', 'likesmsn_api');
define('DB_PASS', 'likesmsn_api');
define('LIFF_SHARE_ID', '2008680740-0nYlU5tK');

// App Configuration
define('APP_NAME', 'LINECRM');
define('APP_URL', 'https://www.l.poppyedc.xyz');
define('BASE_URL', 'https://www.l.poppyedc.xyz');
define('TIMEZONE', 'Asia/Bangkok');

// LINE API (ตั้งค่าผ่านหน้า Admin)
define('LINE_CHANNEL_ACCESS_TOKEN', '');
define('LINE_CHANNEL_SECRET', '');

// OpenAI (Optional)
define('OPENAI_API_KEY', '');

// Telegram Notifications (Optional)
define('TELEGRAM_BOT_TOKEN', '');
define('TELEGRAM_CHAT_ID', '');

// Table Names
define('TABLE_USERS', 'users');
define('TABLE_GROUPS', 'groups');

// Initialize
date_default_timezone_set(TIMEZONE);
