<?php
/**
 * LINE CRM Pharmacy - Configuration
 * Generated by Installation Wizard on 2026-01-21 03:09:00
 */

mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');

error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Database
define('DB_HOST', 'localhost');
define('DB_NAME', 'zrismpsz_cny');
define('DB_USER', 'zrismpsz_cny');
define('DB_PASS', 'zrismpsz_cny');

// Application
define('APP_NAME', 'Agentic line');
define('APP_URL', 'https://cny.re-ya.com');
define('BASE_URL', 'https://cny.re-ya.com');
define('TIMEZONE', 'Asia/Bangkok');

// LINE API (ตั้งค่าผ่านหน้า Admin)
define('LINE_CHANNEL_ACCESS_TOKEN', '');
define('LINE_CHANNEL_SECRET', '');

// Table Names
define('TABLE_USERS', 'users');
define('TABLE_GROUPS', 'groups');
// Next.js API Integration
// URL ของ Next.js app (ปรับตาม environment)
define('NEXTJS_API_URL', 'https://inbox.re-ya.com');
// Secret key สำหรับ authentication (ใช้ค่าเดียวกับ Next.js INTERNAL_API_SECRET)
define('INTERNAL_API_SECRET', 'UIFW4a63EGivOlJi4ulxBmaV+0S5WpS5i3ofQqzIOhI=');

// ============================================================================
// Odoo ERP Integration Configuration
// ============================================================================

// Environment: 'staging' or 'production'
// Force production for cny.re-ya.com
define('ODOO_ENVIRONMENT', 'production');

// Staging Configuration
define('ODOO_STAGING_API_BASE_URL', 'https://stg-erp.cnyrxapp.com');
define('ODOO_STAGING_API_KEY', getenv('ODOO_STAGING_API_KEY') ?: '');
define('ODOO_STAGING_WEBHOOK_SECRET', getenv('ODOO_STAGING_WEBHOOK_SECRET') ?: '');

// Production Configuration
define('ODOO_PRODUCTION_API_BASE_URL', 'https://erp.cnyrxapp.com');
define('ODOO_PRODUCTION_API_KEY', getenv('ODOO_PRODUCTION_API_KEY') ?: '5pG-doAH1EEqHXurM3t466WAgKRYemmK7FANAB74o5A');
define('ODOO_PRODUCTION_WEBHOOK_SECRET', getenv('ODOO_PRODUCTION_WEBHOOK_SECRET') ?: 'cny_reya_webhook_3226e48c7c053b4af44011651f2d3cfb');

// Active Configuration (based on environment)
define(
    'ODOO_API_BASE_URL',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_BASE_URL
    : ODOO_STAGING_API_BASE_URL
);

define(
    'ODOO_API_KEY',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_API_KEY
    : ODOO_STAGING_API_KEY
);

define(
    'ODOO_WEBHOOK_SECRET',
    ODOO_ENVIRONMENT === 'production'
    ? ODOO_PRODUCTION_WEBHOOK_SECRET
    : ODOO_STAGING_WEBHOOK_SECRET
);

// Odoo API Settings
define('ODOO_API_TIMEOUT', 30); // seconds
define('ODOO_API_RATE_LIMIT', 60); // requests per minute
define('ODOO_WEBHOOK_TIMEOUT', 5); // seconds - must respond within this time

// Odoo Product API credentials (for /ineco_gc endpoints)
define('CNY_ODOO_API_USER', getenv('CNY_ODOO_API_USER') ?: '');
define('CNY_ODOO_USER_TOKEN', getenv('CNY_ODOO_USER_TOKEN') ?: '');

// Webhook URL (for Odoo team reference)
define('ODOO_WEBHOOK_URL', APP_URL . '/api/webhook/odoo.php');

// LINE Account Mode for Odoo Integration
// 'shared' = ค้นหา user จากทุก line_account_id ในระบบ
define('ODOO_LINE_ACCOUNT_MODE', 'shared');

date_default_timezone_set(TIMEZONE);